### ISSUE TITLE
Module 14 - 1N5818 ?

### ISSUE THREAD

**Issue by cpyne** [schlae/EMP-20Module#3]
Could you confirm what the component is in module 14?   Is it really this?   

https://www.mouser.com/ProductDetail/STMicroelectronics/1N5818?qs=JV7lzlMm3yJEIYWKtht%2FsQ%3D%3D

**Comment by schlae** [comment]
yes.

**Comment by cpyne** [comment]
Great.  Thank you.  I was mixed up by the mention of the other components being surface mounted and assumed this one would need to be too.  Thanks for the clarification.
